# Generated by Django 5.0.4 on 2024-04-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CycleType',
            fields=[
                ('ct_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ct_tname', models.CharField(max_length=8, verbose_name='Тип цикла')),
            ],
            options={
                'verbose_name': 'Типы цикла, применяемые в системе',
                'verbose_name_plural': 'Типы цикла, применяемые в системе',
                'db_table': 'cycle_type',
            },
        ),
        migrations.CreateModel(
            name='Holes',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=50)),
                ('subgroup_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('condition', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithClassificationPredictions',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('locations', models.TextField()),
                ('classification', models.TextField()),
                ('dimension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WellTimelineFrames',
            fields=[
                ('wtf_wtl_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор (номер) серии')),
                ('wtf_ed_uuid', models.UUIDField(verbose_name='Идентификатор эмбриона')),
                ('wtf_rel_focus', models.IntegerField(verbose_name='Относительная фокальная плоскость')),
                ('wtf_frame', models.BinaryField(verbose_name='Кадр (bmp)')),
                ('wtf_dif', models.IntegerField(default=0, verbose_name='Разница с предыдущим кадром')),
                ('wtf_stabilized', models.BooleanField(default=False, verbose_name='Признак выполнения стабилизации')),
            ],
            options={
                'verbose_name': 'Кадры серии изображений',
                'verbose_name_plural': 'Кадры серий изображений',
                'db_table': 'well_timeline_frames',
                'unique_together': {('wtf_wtl_id', 'wtf_ed_uuid', 'wtf_rel_focus')},
            },
        ),
    ]
