# Generated by Django 5.0.3 on 2024-03-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymorpho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subgroup_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
