# Generated by Django 5.0.3 on 2024-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymorpho', '0002_embryo_wholeimage_embryoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='embryo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название эмбриона'),
        ),
        migrations.AlterField(
            model_name='embryo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
